### ISSUE TITLE
vue 文件 <style> 标签内不支持？

### ISSUE THREAD

**Issue by sunnywanggit** [moesuiga/vscode-less-variable-helper#4]
vue 文件 <style> 标签内不支持？

**Comment by moesuiga** [comment]
@sunnywanggit  很抱歉刚看到消息，作为一个没人关注的小透明，没想到也会有收到消息的一天。
至于你提到的 Vue 文件，目前是不支持的。因为一开始只是对单独的less文件做的处理，感觉也没什么人用，就是方便自己的一个工具，所以之前也没有什么迭代的需求。
支持Vue文件style这个功能，我后面会抽空添加的，到时候可能还要麻烦你做个「测试员」了😀
最后感谢你的使用与支持。

**Comment by moesuiga** [comment]
@sunnywanggit  
`0.0.13` 版已发布，期待你的反馈 ღ( ´･ᴗ･` )
#5
